title: Nicolas Mohnblatt
logo: /assets/images/placeholder.jpg
description: >-
  Researcher in applied cryptography and privacy-enhancing technologies. Welcome to my home page!
baseurl: ""
twitter_username: nico_mnbl
github_username:  nmohnblatt

github:
  is_project_page: false

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed

